#+TITLE: My Personal Options
#+AUTHOR: Matthew L. Fidler
* El-get Packages I use
#+begin_src emacs-lisp
  (setq my-lisp-packages
        (list 'magit  'textmate-to-yas 'ess 'yaoddmuse 'w32-browser 'ntcmd
              'org-table-comment  'ess-smart-underscore 'el-autoyas
              'org-cua-dwim 'nsis-mode 'ido-ubiquitous 'ergoemacs-keybindings
              'lib-requires 'ssh))
  ;; 'header2
  ;; 'ac-R
  ;; 'xahk-mode  'ntcmd  'lib-requires 'linum-off
  ;;'fold-dwim-org 'fold-dwim  'el-autoyas 'cygwin-mount
  ;;'ac-R  'marmalade
  ;; 'sumatra-forward
  ;; 'clojure-mode
  ;; 'org-outlook
  ;; 'auctex
  ;; 'smart-operator
  (el-get 'sync my-lisp-packages)
  
#+end_src
* Keyboard Bindings

* Things I use
This is a list of the things that I use and would like to load:
#+begin_src emacs-lisp
  (mapc
   (lambda(item)
     (kicker-load (concat "kicker-" item ".org")))
   (list
    "lisp" "eshell" "ess" "org" "nxhtml" "cygwin" "latex"))
  
#+end_src

* Tabbar-ruler
I want the tool-bar to be a popup ruler.  That is it only shows when
you move your ruler to the top of the frame.  
#+BEGIN_SRC emacs-lisp
  (setq tabbar-ruler-global-tabbar 't) ; If you want tabbar
  (setq tabbar-ruler-global-ruler 't) ; if you want a global ruler
  (setq tabbar-ruler-popup-menu 't) ; If you want a popup menu.
  (setq tabbar-ruler-popup-toolbar 't) ; If you want a popup toolbar
#+END_SRC

* Header2
#+BEGIN_SRC emacs-lisp
(add-hook 'emacs-lisp-mode-hook 'auto-make-header)
#+END_SRC

* Misc
** User Name
I like to have my user-name set.  It fixes some issues in Emacs.
#+BEGIN_SRC emacs-lisp
(setq user-full-name "Matthew L. Fidler")
(setq user-mail-address "matthew.fidler@gmail.com")
#+END_SRC
** RefTeX
I'm setting my ref-TeX to my database of articles
#+BEGIN_SRC emacs-lisp
  (setq reftex-default-bibliograph '("~/Work/Articles/generalOcular.bib"))
#+END_SRC
* IDO hacks
See http://www.emacswiki.org/emacs/InteractivelyDoThings
** Display Completions Vertically
I like the look.  I don't like the arrow keys not doing what I expect...
#+BEGIN_SRC emacs-lisp
  (setq ido-decorations (quote ("\n-> " "" "\n   " "\n   ..." "[" "]" " [No match]" " [Matched]" " [Not readable]" " [Too big]" " [Confirm]")))
  
  (defun ido-disable-line-trucation () (set (make-local-variable 'truncate-lines) nil))
  (add-hook 'ido-minibuffer-setup-hook 'ido-disable-line-trucation)
#+END_SRC


** Preventing auto-searches unless called explicitly
#+BEGIN_SRC emacs-lisp
  ;; disable auto searching for files unless called explicitly
  (setq ido-auto-merge-delay-time 99999)
  
  (define-key ido-file-dir-completion-map (kbd "C-c C-s") 
    (lambda() 
      (interactive)
      (ido-initiate-auto-merge (current-buffer))))
#+END_SRC

* Emacs Speaks NONMEM
I use esn
#+BEGIN_SRC emacs-lisp
  (require 'esn-start nil t)
#+END_SRC
* Emacs Speaks Statistics
I use ssh for remote access.  However, I want to use plink if on
windows
#+BEGIN_SRC emacs-lisp
  (when (getenv "GIT_SSH")
    (setq ssh-program (getenv "GIT_SSH")))
#+END_SRC

* Testing Out
** Marmalade
I need to set the default server....
#+BEGIN_SRC emacs-lisp
  (setq marmalade-server "http://marmalade-repo.org/")
#+END_SRC

* Ssh when in windows
When in windows use putty instead of ssh for the ssh package.
#+BEGIN_SRC emacs-lisp
  (when (eq system-type 'windows-nt)
    (setq ssh-program "plink"))
  
#+END_SRC

